name: .NET
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          source-url: https://nuget.pkg.github.com/armunro/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Build
        run: dotnet build --configuration Release
      - name: Pack NuGet package
        run: dotnet pack --configuration Release --no-build --output ./nuget
      - name: Publish to GitHub Packages
        run: dotnet nuget push ./nuget/*.nupkg --skip-duplicate --no-symbols true
